version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: lightit-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: lightit-app
    restart: always
    ports:
      - '4000:3000'
    depends_on:
      - db
    env_file:
      - .env

volumes:
  pgdata:
